Skills | FoV
OpaqueSunset/LighthouseRelay pull request #6
Opened 2023-04-02 19:35 UTC by ProbablyCarl

This works with some serious tweaking. Or did, at least, on earlier versions of Nebula. Couldn't get it fixed for this repo specifically, but it's here as a proof of concept.
Torn out of IS12, I believe. It's been years since I nabbed this.
- - -
Content:
 - FoV / Masked View
 - Skills
- - -

2023-04-02 20:39 UTC, out-of-phaze requested changes
Skills system needs to be removed, Nebula already has one.

Some other code improvements for the vision cone modpack. Also maybe rename it so it's clearer what it does?

2023-04-02 20:39 UTC, out-of-phaze commented on mods/content/agony_mode/overrides/human.dm
> +	..()
```suggestion
```
This is meaningless here since it's not inside a proc.

2023-04-02 20:39 UTC, out-of-phaze commented on mods/content/agony_mode/overrides/human.dm
> +		update_mask_vision(wear_mask)
```suggestion
	var/obj/item/clothing/mask/mask = get_equipped_item(slot_wear_mask_str)
	if(istype(mask))
		update_mask_vision(mask)
```

2023-04-02 20:39 UTC, out-of-phaze commented on mods/content/agony_mode/overrides/human.dm
> +	if(istype(src.head, /obj/item/clothing/head))
```suggestion
	var/obj/item/clothing/head/helmet = get_equipped_item(slot_wear_head_str)
	if(istype(helmet))
		update_helmet_vision(helmet)
```

2023-04-03 05:55 UTC, out-of-phaze requested changes

2023-04-03 05:55 UTC, out-of-phaze commented on mods/content/fov_module/overrides/human.dm
> +	..()
```suggestion
```

2023-04-03 21:13 UTC, ProbablyCarl commented
This breaks ladders somehow. I think.

2023-04-03 21:37 UTC, PolymorphBlue approved these changes
Looks reasonable.  I don't see any immediate issues.

2023-04-03 21:58 UTC, PolymorphBlue requested changes
Return values need to be checked, please!

2023-04-03 22:17 UTC, PolymorphBlue submitted a review, later dismissed
Looks reasonable!

2023-04-04 00:30 UTC, merged